# Generated by Django 2.0.8 on 2019-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('Email', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
