# Generated by Django 2.0.8 on 2019-09-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='complain',
        ),
    ]
