# Generated by Django 2.0.8 on 2019-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20190916_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
